title: Louis Aubert Andriawan # your name (or website title) here
logo: "Foto Louis.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello, my name is Louis Aubert Andriawan. 
  <br><br>
  I'm currently studied at Brawijaya University as Statistics student.
  <br><br>
  <a href="https://www.linkedin.com/in/louis-aubert-andriawan-145162269/"> My LinkedIn </a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
